<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20250926121635 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial schema for users, project, application tables (PostgreSQL)';
    }

    public function up(Schema $schema): void
    {
        // this migration is autogenerated to be safe for PostgreSQL
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'postgresql', 'Migration can only be executed safely on postgresql.');

        // users
        $this->addSql('CREATE TABLE users (id SERIAL NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, name VARCHAR(100) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');

        // project
        $this->addSql('CREATE TABLE project (id SERIAL NOT NULL, owner_id INT NOT NULL, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2FB3D0EE7E3C61F9 ON project (owner_id)');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE7E3C61F9 FOREIGN KEY (owner_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        // application
        $this->addSql('CREATE TABLE application (id SERIAL NOT NULL, project_id INT NOT NULL, applicant_id INT NOT NULL, message TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A45BDDC1166D1F9C ON application (project_id)');
        $this->addSql('CREATE INDEX IDX_A45BDDCCCBF1154 ON application (applicant_id)');
        $this->addSql('ALTER TABLE application ADD CONSTRAINT FK_A45BDDC1166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE application ADD CONSTRAINT FK_A45BDDCCCBF1154 FOREIGN KEY (applicant_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'postgresql', 'Migration can only be executed safely on postgresql.');

        $this->addSql('ALTER TABLE application DROP CONSTRAINT FK_A45BDDC1166D1F9C');
        $this->addSql('ALTER TABLE application DROP CONSTRAINT FK_A45BDDCCCBF1154');
        $this->addSql('ALTER TABLE project DROP CONSTRAINT FK_2FB3D0EE7E3C61F9');

        $this->addSql('DROP TABLE application');
        $this->addSql('DROP TABLE project');
        $this->addSql('DROP TABLE users');
    }
}
