parameters:
  env(RECAPTCHA_SITE_KEY): ''
  env(RECAPTCHA_SECRET): ''

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/Kernel.php'
      - '../src/Entity/'